### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by jiluofu1** [Lin-Kayla/subjectivity-sketch-reid#3]
Is this error due to the incorrect configuration of my environment? Can I force them into a form that multiplies? 

File "/home/zhongr/PycharmProjects/subjectivity-sketch-reid-main/model.py", line 228, in forward
loss = torch.mean(comask_pos.squeeze(1) * self.criterion(feat, feat_recon_pos, feat_recon_neg))
RuntimeError: The size of tensor a (9) must match the size of tensor b (18) at non-singleton dimension 2

**Comment by Lin-Kayla** [comment]
Hi! Our Pytorch version is 1.12.1, the behaviour within nn.TripletMarginLoss may differ across PyTorch versions. You can either change your pytorch version or reshape tensors prior to passing them through nn.TripletMarginLoss.
